name: Android CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Build client SDK AAR
      run: ./gradlew :csfe:assembleRelease
    
    - name: Upload client SDK AAR
      uses: actions/upload-artifact@v3
      with:
        name: csfe-release
        path: csfe/build/outputs/aar/csfe-release.aar
    
    - name: Build sample app APK
      run: ./gradlew :app:assembleDebug
    
    - name: Upload sample app APK
      uses: actions/upload-artifact@v3
      with:
        name: sample-payment-app
        path: app/build/outputs/apk/debug/app-debug.apk
